### ISSUE TITLE
appears unstyled with react-toolbox 2.0 + meteor 1.5

### ISSUE THREAD

**Issue by shenrenguo** [nathantreid/meteor-css-modules#103]
@nathantreid
I cloned @neoromantic ‘s [test repo #90 ](https://github.com/nathantreid/meteor-css-modules/issues/90), and upgrade to meteor 1.5，also installed postcss plugins you mentioned above. But, still appears unstyled.

here is the test repo https://github.com/shenrenguo/meteor-cssmodules-reacttoolbox.git
 can you give me some help?

**Comment by neoromantic** [comment]
I have troubles with getting react toolbox with css modules and meteor 1.5 to work too. 

It appears unstyled. 

Отправлено с iPhone

**Comment by teknologist** [comment]
Same here

**Comment by akanix42** [comment]
Thanks for the reports - I should be able to look at this in the next couple days.

**Comment by Furqankhanzada** [comment]
@nathantreid any update on it ?

**Comment by akanix42** [comment]
Unfortunately this week turned out to be super busy for me, so I haven't looked at it yet.

**Comment by josephtactica** [comment]
Hi @nathantreid, just want to check in on this issue... Thanks.

**Comment by akanix42** [comment]
It appears that the transpilation of ES modules has changed in Meteor 1.5, and the `__esModule` property has been replaced with a `Symbol`.
React-Toolbox relies on that property to properly import the files. I'll have to do more checking to make sure my fix doesn't break anything else, but in the meantime, please try the following version - it works for me with react-toolbox: `nathantreid:css-modules@2.7.4-beta.3`.
