### ISSUE TITLE
Cannot install or update to latest version

### ISSUE THREAD

**Issue by ddeklerk** [nathantreid/meteor-css-modules#11]
Whenever I try to update from `1.0.0-beta.9` or install using `meteor add nathantreid:css-modules` I get the following error:

```
While checking for nathantreid:css-modules@1.0.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

I am using version 1.3.1 of Meteor so I should be able to install version 1.0.0, right?

**Comment by akanix42** [comment]
Because node-sass is included, there is an extra publishing step for each architecture, which hadn't been completed when you tried to install it.
I've now built for all platforms except OS X, since the Meteor build servers still aren't cooperating there: meteor/meteor#6567

**Comment by ddeklerk** [comment]
Great to hear. I just installed it successfully on my Windows computer.
