### ISSUE TITLE
scss files eagerly loaded even in imports folder

### ISSUE THREAD

**Issue by ddeklerk** [nathantreid/meteor-css-modules#12]
Now that css-modules finally works with the imports folder I noticed that I did not need to import my stylesheets from the imports folder. This means that any scss files that live there will be eagerly loaded by Meteor.

Let's say I define a whole library of components all using css-modules for the styling. Whenever I don't use one of those (it is not imported in my javascript), the styling is still loaded and compiled into the main stylesheet. You can see how this can cause problems. The least of which is that the final stylesheets can get very bloated.

**Comment by akanix42** [comment]
I'm pretty sure I know how to fix this, so I should get to it pretty soon. I just need to work with the Meteor 1.3 way of adding lazy stylesheets.

**Comment by akanix42** [comment]
Fixed in 1.0.1 (just released to Atmosphere).
