### ISSUE TITLE
SSR problem

### ISSUE THREAD

**Issue by proxiper** [nathantreid/meteor-css-modules#13]
Hello.

I've set:

```
{
  "cssModules": {
    "specificArchitecture": false
  }
}
```

but now getting this:

```
TypeError: Object [object Object] has no method 'addStyles'
  at meteorInstall.imports.ui.app.m.css (.meteor/local/build/programs/server/app/app.js:112:22)
  at fileEvaluate (packages/modules-runtime.js:158:9)
  at require (packages/modules-runtime.js:92:16)
  at meteorInstall.imports.ui.app.jsx (imports/ui/app.jsx:5:1)
  at fileEvaluate (packages/modules-runtime.js:158:9)
  at require (packages/modules-runtime.js:92:16)
  at meteorInstall.imports.startup.routes.jsx (imports/startup/routes.jsx:4:1)
  at fileEvaluate (packages/modules-runtime.js:158:9)
  at require (packages/modules-runtime.js:92:16)
  at meteorInstall.server.main.jsx (server/main.jsx:1:1)
```

I'm using:
meteor 1.3.1
nathantreid:css-modules@1.0.1
kadira:flow-router-ssr@3.12.2
mac os 10.11.2

**Comment by akanix42** [comment]
Thanks for the report!
This is fixed in 1.0.2.

**Comment by proxiper** [comment]
Thank you!

Now it works, but the styles apply only after loading of the scripts. So, it's good for bots, but not for people. 

Also it takes a lot of time to reload a server. In this topic https://github.com/gadicc/meteor-react-hotloader/issues/26 @gadicc has found a great solution and radically improved a reloading speed. Maybe this will help you to create a better solution too.

**Comment by akanix42** [comment]
> Now it works, but the styles apply only after loading of the scripts. So, it's good for bots, but not for people.

In Meteor 1.3, lazy loaded CSS files are converted into JS files and wrapped in the addStyles method which adds the styles to the DOM. I'll have to play around with FlowRouter to see if they've come up with a way to handle this.

> Also it takes a lot of time to reload a server

I feel your pain. @gadicc has done some _really_ awesome work, but AFAIK it only works for React right now. That's not to say I won't look into it (I will) but I think reloading other JS files might be quite the large project in itself.

**Comment by gadicc** [comment]
Thanks, guys!  Yes, @nathantreid is correct, although I do plan to expand this to [more general HMR](https://github.com/gadicc/meteor-react-hotloader/issues/8).  It's not too much work for a modest implementation, just haven't had a chance in light of more important improvements.  I hope over the next month.  And in that case, since it seems that css-modules (npm) [supports hotloading](https://github.com/css-modules/webpack-demo/issues/8), I'm sure we can get it going.

**Comment by gadicc** [comment]
@proxiper, no ETA but this will come eventually I think :)  https://github.com/nathantreid/meteor-css-modules/pull/26

**Comment by RafaelVidaurre** [comment]
I'm getting this version on 2.1.0, I'm importing styles from a local package

**Comment by RafaelVidaurre** [comment]
This stopped happening after removing `fourseven:scss`
