### ISSUE TITLE
Postcss plugins don't work

### ISSUE THREAD

**Issue by proxiper** [nathantreid/meteor-css-modules#14]
I tried to add some plugins (autoprefixer or css-next) to the package.json, but nothing happens. 

It works in demo https://github.com/nathantreid/css-modules-demo-meteor-1.3 
but after update to nathantreid:css-modules@1.0.1 or 1.0.2 the app stops working. Looks like it can't find "postcss-nested" and crashing because of that.

**Comment by akanix42** [comment]
Sorry about that, the main documentation was out-of-date, so I've updated it. I'll update the demo project soon.

**Comment by akanix42** [comment]
The demo project has been updated.

**Comment by proxiper** [comment]
Now it works! Thank you!
