### ISSUE TITLE
No compatible binary build found for this package.

### ISSUE THREAD

**Issue by wojtkowiak** [nathantreid/meteor-css-modules#16]
Hey,

just got this trying to add the package to meteor 1.3.1 project:
`While checking for nathantreid:css-modules@1.0.3:
error: No compatible binary build found for this package. Contact the package author and ask them to publish
it for your platform.
`
Platform:
Xubuntu 14.04 64bit

**Comment by wojtkowiak** [comment]
If I can help in any way, let me know :smile:

**Comment by akanix42** [comment]
Thanks! Turns out the Meteor build server shut off partway through publishing for Linux 64bit... you should be able to pull down the package now.
