### ISSUE TITLE
 The problem with composition from the imports folders

### ISSUE THREAD

**Issue by proxiper** [nathantreid/meteor-css-modules#18]
When I compose something from `imports` folders, the package generates class names, but doesn't append styles to the generated css file. So, it works only if I duplicate importing in some jsx file like: `import '../imports/theme/colors.m.css'`

meteor 1.3.1
nathantreid:css-modules@1.0.3
kadira:flow-router-ssr@3.12.2
mac os 10.11.2

**Comment by akanix42** [comment]
Wow, you're just finding all the bugs! I really appreciate these reports.

**Comment by akanix42** [comment]
The solution here is rather straightforward: CSS Modules needs to track the composes and add them as imports to the output JS files. I've almost got this fixed, just need to find the time - then I'll be able to move on to #17.

**Comment by akanix42** [comment]
This should be resolved in version 1.1.1 - are you still experiencing issues?
