### ISSUE TITLE
Stylus support

### ISSUE THREAD

**Issue by pward123** [nathantreid/meteor-css-modules#19]
Would you accept a PR that adds stylus support?

**Comment by akanix42** [comment]
I'd be happy too! In addition to the Stylus processing, there needs to an enableStylusCompilation option that defaults to `[ '.styl' ]` (or whatever other stylus-specific extensions there are, I'm not too familiar with it), like I've done with Sass: 

> To enable Sass compilation, set the aforementioned extensions property to ['scss', 'sass']. If you are using a different file extension, set it in the extensions property, and also set the enableSassCompilation property, which defaults to ['scss', 'sass'].
