### ISSUE TITLE
Move binary deps to another package

### ISSUE THREAD

**Issue by gadicc** [nathantreid/meteor-css-modules#27]
Not sure if you know this trick, but it will change your life :)  Put `node-sass` and any other deps in their own package, say `css-modules-binary-deps`, and `publish-for-arch` that.  Then `api.use()` that binary dep package and get `node-sass` from there.  And that's the last-time you'll have to `publish-for-arch` until you need to update any of those binary deps again.

**Comment by akanix42** [comment]
I tried that, and I still got the message that I had to publish-for-arch. I did some digging and found [this old issue](https://github.com/meteor/meteor/issues/2798) stating that publish-for-arch is still required for build plugins that use a binary package.

**Comment by gadicc** [comment]
Oh wow, please tell me you tried this a while back and didn't waste time on this now :>  It's a bit embarrassing considering I was involved in that issue you mentioned!  But yeah it was from over a year ago.

**Comment by akanix42** [comment]
Yeah, it was about 2 weeks ago, when I got rather annoyed with having to publish-for-arch every time I made a little update. I've even considered trying to remove the npm dependencies and require the user to npm install them - but I think instead I just need to find the time to automate the build process.
Wouldn't be half as bad if the Meteor OS X build servers hadn't been so unstable lately.

**Comment by gadicc** [comment]
Ugh yeah this was driving me mad too :/  Maybe I should move my bitcoin mining operation from the OS X build servers to the Ubuntu ones, which seem much more reliable ^_^
