### ISSUE TITLE
Can't install 1.1.2 on Meteor 1.3.2.4

### ISSUE THREAD

**Issue by icukaegbu** [nathantreid/meteor-css-modules#30]
Can's seem to install 1.1.2 on OS X 10.11.4, gives the error message below: 
**"While checking for nathantreid:css-modules@1.1.2:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform."**

Trying to run React-Toolbox 0.16 with React v15 and Meteor 1.3.2.4. My package.json is as shown below:
{
  "name": "visitor-management",
  "private": true,
  "scripts": {
    "testonly": "mocha client/**/tests/**/_.js --compilers js:babel-core/register",
    "test": "npm run testonly",
    "test-watch": "npm run testonly -- --watch --watch-extensions js,jsx"
  },
  "devDependencies": {
    "autoprefixer": "^6.3.6",
    "babel-core": "6.x.x",
    "babel-plugin-react-require": "2.x.x",
    "babel-polyfill": "6.x.x",
    "babel-preset-es2015": "6.x.x",
    "babel-preset-react": "6.x.x",
    "babel-preset-stage-2": "6.x.x",
    "babel-root-slash-import": "1.x.x",
    "chai": "3.x.x",
    "enzyme": "2.x.x",
    "eslint": "2.8.x",
    "eslint-plugin-react": "5.0.x",
    "mocha": "2.x.x",
    "react-addons-test-utils": "^15.0.1",
    "sinon": "1.17.x"
  },
  "dependencies": {
    "chart.js": "^1.1.1",
    "domready": "^1.0.8",
    "mantra-core": "^1.5.0",
    "material-ui": "^0.15.0-beta.1",
    "meteor-node-stubs": "~0.2.3",
    "normalize.css": "^4.1.1",
    "react": "^15.0.1",
    "react-addons-css-transition-group": "^15.0.1",
    "react-chartjs": "^0.7.3",
    "react-dazzle": "^1.0.2",
    "react-dom": "^15.0.1",
    "react-mounter": "^1.2.0",
    "react-tap-event-plugin": "^1.0.0",
    "react-toolbox": "^0.16.2"
  },
  "cssModules": {
    "extensions": [
      "scss", "sass"
    ],
    "globalVariables": [
      "node_modules/react-toolbox/lib/_colors.scss",
      { "theme-building": true },
      "client/toolbox-theme.scss"
    ],
    "outputJsFilePath": {
      "._node_modules/.*": "{dirname}/{basename}.js"
    },
    "explicitIncludes": [
      "node_modules/react-toolbox"
    ]
  }
}

Prior error with 1.1.1 was **/Users/ikedi/.meteor/packages/coffeescript/.1.0.17.nlotic++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
TypeError: Cannot call method 'substr' of undefined**

**Comment by thomasgalibert** [comment]
same issue on my ubuntu server with meteor 1.3.2.4

**Comment by rainum** [comment]
Same issue on OS X 10.11.4:

``` bash
While checking for nathantreid:css-modules@1.1.2:
error: No compatible binary build found for this package. Contact the package author and ask
them to publish it for your platform.
```

**Comment by newswim** [comment]
Ditto, if I recall correctly this is a problem with Atmosphere.

**Comment by akanix42** [comment]
Meteor requires you to use their build servers for publish packages with binary dependencies (like node-sass). Unfortunately, the Meteor build servers are unstable. Reviewing the logs it looks like the OS X and Linux publishing servers shut off right before publishing the package. I'll re-run these shortly.

I'm considering removing node-sass from the package and instead requiring the user to `npm install` it if they want SCSS support; that would alleviate this issue and allow you to choose your node-sass version; right now I'm stuck on 3.4.2 since React Toolbox doesn't work with later versions.

**Comment by akanix42** [comment]
@thomasgalibert: Linux is good to go now.

OSX is still kicking me off partway through the process, and the MDG response to this is "This does happen sometimes" so I'll wait a while and try again.

**Comment by akanix42** [comment]
1.1.2 has been published for OS X.
