### ISSUE TITLE
Causes issues with react-select

### ISSUE THREAD

**Issue by genyded** [nathantreid/meteor-css-modules#33]
Has anyone had success getting this to work with [react-select](https://github.com/JedWatson/react-select) installed as well? It may be issues with the sass for that component, but it works fine wihout css-modules installed. I am wondering if the is a way to exclude the react select stuff from being seen in the packages.json config or if anyone else has any ideas. Here is the output with both installed and either works fine without the other...

```
=> Started proxy.
=> Started MongoDB.
[Error: File 'control' not found at any of the following paths: ["control","cont
rol.scss","control.sass","./_control","./_control.scss","./_control.sass"]]
[Error: File 'spinner' not found at any of the following paths: ["spinner","spin
ner.scss","spinner.sass","./_spinner","./_spinner.scss","./_spinner.sass"]]
[Error: File 'select' not found at any of the following paths: ["select","select
.scss","select.sass","./_select","./_select.scss","./_select.sass"]]
[Error: File 'mixins' not found at any of the following paths: ["mixins","mixins
.scss","mixins.sass","./_mixins","./_mixins.scss","./_mixins.sass"]]
=> Errors prevented startup:

   While processing files with nathantreid:css-modules (for target
   web.browser):

   \AppData\Local\.meteor\packages\nathantreid_css-modules\1.1.2\p
lugin.mss.os.windows.x86_32\npm\node_modules\meteor\mss\node_modules\postcss\lib
\input.js:61:22:
  \AppData\Local\.meteor\projects\meteor-mantra-kickstarter-devel
op\node_modules\react-select\scss\control.scss:309:1:
   Unknown word
   at Input.error
   (\AppData\Local\.meteor\packages\nathantreid_css-modules\1.1.2\
plugin.mss.os.windows.x86_32\npm\node_modules\meteor\mss\node_modules\postcss\li
b\input.js:61:22)
   at Parser.unknownWord
   (C:\Users\genyd\AppData\Local\.meteor\packages\nathantreid_css-modules\1.1.2\
plugin.mss.os.windows.x86_32\npm\node_modules\meteor\mss\node_modules\postcss\li
b\parser.js:457:26)
   at Parser.word
   (\AppData\Local\.meteor\packages\nathantreid_css-modules\1.1.2\
plugin.mss.os.windows.x86_32\npm\node_modules\meteor\mss\node_modules\postcss\li
b\parser.js:174:14)
   at Parser.loop
   (\AppData\Local\.meteor\packages\nathantreid_css-modules\1.1.2\
plugin.mss.os.windows.x86_32\npm\node_modules\meteor\mss\node_modules\postcss\li
b\parser.js:60:26)
   at parse
   (\AppData\Local\.meteor\packages\nathantreid_css-modules\1.1.2\
plugin.mss.os.windows.x86_32\npm\node_modules\meteor\mss\node_modules\postcss\li
b\parse.js:26:12)
   at new LazyResult
   (\AppData\Local\.meteor\packages\nathantreid_css-modules\1.1.2\
plugin.mss.os.windows.x86_32\npm\node_modules\meteor\mss\node_modules\postcss\li
b\lazy-result.js:61:24)
   at Processor.process
   (\AppData\Local\.meteor\packages\nathantreid_css-modules\1.1.2\
plugin.mss.os.windows.x86_32\npm\node_modules\meteor\mss\node_modules\postcss\li
b\processor.js:34:16)
   at CssModulesProcessor.load
   (packages/mss/css-modules-processor.js:74:5)
   at packages/mss/css-modules-processor.js:33:10
   at tryCallTwo
   (C:\Users\genyd\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.wind
ows.x86_32\dev_bundle\lib\node_modules\promise\lib\core.js:45:5)
   at doResolve
   (\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.wind
ows.x86_32\dev_bundle\lib\node_modules\promise\lib\core.js:171:13)
   at new Promise
   (\Appdata\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.wind
ows.x86_32\dev_bundle\lib\node_modules\promise\lib\core.js:65:3)
   at CssModulesProcessor.processInternal
   (packages/mss/css-modules-processor.js:28:11)
   at CssModulesProcessor.process
   (packages/mss/css-modules-processor.js:18:26)
   at CssModulesBuildPlugin.processFile
   (packages/mss/css-modules-build-plugin.js:206:22)
   at Array.forEach (native)
   at CssModulesBuildPlugin.compileCssModules
   (packages/mss/css-modules-build-plugin.js:198:34)
   at CssModulesBuildPlugin.processFilesForTarget
   (packages/mss/css-modules-build-plugin.js:58:21)


   While minifying app stylesheet:
   app/node_modules/react-select/scss/components.scss.css:315:44: missing
   '{'

=> Your application has errors. Waiting for file change.
```

**Comment by rainum** [comment]
Same issue here.

@genyded it works fine without meteor-css-modules installed because it uses precompiled `react-select/dist/react-select.css` by default. Error occurs when meteor-css-modules tries to compile react-select's scss styles.

@nathantreid could you please add option which allows to ignore some paths? Something like `ignorePaths` to the options.

**Comment by genyded** [comment]
Thanks for the info and I figured as much. We were trying to use this to add react-toolbox, but we are on a tight timeline, so we're trying other options and may revisit this later so an 'exclude' option would be great. It's really cool someone took the time to try and help things like react toolbox work in Meteor. Kudos Natahan!

**Comment by akanix42** [comment]
@rainum: `ignorePaths` sounds like a good option... I'm adding it to my todo list.

**Comment by clayne11** [comment]
I already created an issue about exactly this: https://github.com/nathantreid/meteor-css-modules/issues/32

**Comment by akanix42** [comment]
@clayne11: Ah, I initially took your issue to be a little different, in that the files were being loaded into the app even though they shouldn't have been since they should have been lazy-loaded but were never referenced. 

Meteor's current build system sends all the files for a registered extension (in this case .scss) to the build plugin, regardless of whether or not they are referenced anywhere in the app. It isn't until the bundling step that the file usage is evaluated and only `import`ed and non-lazy files are bundled.

**Comment by genyded** [comment]
We're trying to move to react toolbox from Material UI because of quality issues and rude team members there, but we also make extensive use of react select throughout our app. Also Meteor is a must for us for the time being. We're already behind because of the move away from Material UI, so it would be cool if we could get react toolbox and react select working together with Meteor soon. 

We also understand most of us open source supporters also have lives and day jobs though, so if this fix has to wait a bit we'll probably go with bootstrap react or something else for now and revisit this later. Great work on this @nathantreid and appreciate how quickly you always follow up!

**Comment by clayne11** [comment]
What I did to get `react-select` working is simply created a Meteor package with the `react-select` code in it. Once this issue is fixed I can go back to use the version from Npm.

**Comment by genyded** [comment]
Brilliant! Any plans to publish it to Atmosphere? The ones out there are outdated and the Select.Async causes issues. We need 1.0.0-beta9+  wrapped. If not we can create our own, but figured why reinvent the wheel.

**Comment by akanix42** [comment]
Sorry for the delay on this - the `ignorePaths` option has been added in 1.2.0. I've documented the new option here: https://github.com/nathantreid/meteor-css-modules/wiki/Package-Options

**Comment by rainum** [comment]
@nathantreid awesome, thanks!
