### ISSUE TITLE
Compress style in production mode

### ISSUE THREAD

**Issue by JWo1F** [nathantreid/meteor-css-modules#34]
**.packages__test-modules_abc** to **.8934ad897647f9** for example (MD5).

**Comment by cristiancedenogallego** [comment]
You can use cssnano for this, please check http://cssnano.co
I suppose that is the reason for not be included

**Comment by akanix42** [comment]
@JWo1F have you tried using https://www.npmjs.com/package/postcss-hash-classname for this? I haven't tried itself, but it looks like it should do the trick.
