### ISSUE TITLE
Remove dependencies of unused npm modules

### ISSUE THREAD

**Issue by comerc** [nathantreid/meteor-css-modules#39]
such as: sass, stylus, sugarss

**Comment by akanix42** [comment]
I'm thinking of switching them to user-installed dependencies so they don't bloat the package (also helps me with package builds).

**Comment by comerc** [comment]
Yes! :) assembling a local copy of the packet is performed for a long time.

**Comment by akanix42** [comment]
As of 2.0.0, the npm packages for sass, stylus, and sugarss are no longer bundled with the package and must be `meteor npm install`ed by the user as needed. [The wik](https://github.com/nathantreid/meteor-css-modules/wiki)i contains instructions on setting each up.
