### ISSUE TITLE
Any plans to support Less?

### ISSUE THREAD

**Issue by skirunman** [nathantreid/meteor-css-modules#44]
Hi Nathan,
Any plans to support Less so it would be possible to easily use [Essence](http://getessence.io/) ([github](https://github.com/Evo-Forge/Essence)) with Meteor 1.3.3?
Thanks!
Jim

**Comment by akanix42** [comment]
I'll add this to my todo list, but it might be a while before I can get to it; alternatively, I will happily accept a pull request that implements it in the way I've done for Sass.

**Comment by StGeass** [comment]
@skirunman https://github.com/nathantreid/meteor-css-modules/pull/78

**Comment by akanix42** [comment]
Closing because the PR was merged months ago but I forgot this issue.
