### ISSUE TITLE
Can camelCase?

### ISSUE THREAD

**Issue by cristiancedenogallego** [nathantreid/meteor-css-modules#45]
Can any option to camelcase selectors?

example: 
.any-element >> anyElement

see https://github.com/webpack/css-loader
css-loader?camelCase

**Comment by akanix42** [comment]
There isn't an option for this yet, I'll have to see what it would take to enable.

**Comment by akanix42** [comment]
You can do this now!
package.json:

``` json
"cssModules": {
  "jsClassNamingConvention": {
    "camelCase": true
  }
}
```

See the [package options wiki page](https://github.com/nathantreid/meteor-css-modules/wiki/Package-Options) for more details.

**Comment by cristiancedenogallego** [comment]
@nathantreid thanks
