### ISSUE TITLE
The README does not demonstrate the .css extension

### ISSUE THREAD

**Issue by adrianmcli** [nathantreid/meteor-css-modules#52]
I read on the Meteor forums ([link](https://forums.meteor.com/t/css-modules-for-meteor-without-webpack/19682/30)) that `.css` extension is now supported so I will not need to use the `.mss` file extension.

However, the README does not reflect that yet. Is this support considered stable yet?

**Comment by akanix42** [comment]
It is! I've updated the README to reflect this.
