### ISSUE TITLE
'No compatible binary build found for this package'

### ISSUE THREAD

**Issue by newswim** [nathantreid/meteor-css-modules#56]
Just upgraded to Meteor 1.3.4.4, are you waiting for 1.4 to publish a new release? Understandable if so, I'm just wondering if this is a fluke. Thanks for your help!

**Comment by akanix42** [comment]
There shouldn't be any need for binary builds anymore. Are you using the latest version (2.1.0)?

**Comment by newswim** [comment]
I just had to re-link node-sass as per the instructions, and include the _outputJsFilePath_ defs in package.json. This is probably because I haven't updated react-toolbox to 1.0 yet. All good!
