### ISSUE TITLE
How to set-up React-Flexbox-Grid

### ISSUE THREAD

**Issue by PolGuixe** [nathantreid/meteor-css-modules#66]
I am having issues to set-up https://github.com/roylee0704/react-flexbox-grid
Errors:

```
Processing Step: SCSS compilation
Unable to compile /Users/PolGuixe/Documents/Developer/Meteor/Apps/tests/Zetoff-Sandbox/node_modules/react-flexbox-grid/doc/app/components/markdown/style.scss
Line: 14, Column: 11
```

and:

```
Errors prevented startup:

   While processing files with nathantreid:css-modules (for target web.browser):
   /Users/PolGuixe/Documents/Developer/Meteor/Apps/tests/Zetoff-Sandbox/node_modules/node-sass/lib/index.js:420:22: CSS modules
   SCSS compiler error: file not found:
   (/Users/PolGuixe/Documents/Developer/Meteor/Apps/tests/Zetoff-Sandbox/node_modules/highlight.js/styles/github-gist.scss)
```

How it should be properly set up?

**Comment by akanix42** [comment]
CSS Modules is trying to process react-flexbox-grid's `doc` folder, which includes a sample app. You need to exclude this folder from processing. You most likely only care about the content of the src folder, so I recommend you also ignore the `spec` and `test` folders.
You can do this using the "ignorePaths" option (see [Package Options](https://github.com/nathantreid/meteor-css-modules/wiki/Package-Options)) for more details.

Something like this should do the trick:
**package.json**

```
"cssModules": {
  "ignorePaths": [
    "node_modules/react-flexbox-grid/(doc|spec|test|)/"
  ]
}
```

**Comment by PolGuixe** [comment]
@nathantreid now the errors had stopped but the package is not working neither. 

This is my configuration: 

```
"cssModules": {
    "extensions": [
      "scss"
    ],
    "globalVariables": [
      "node_modules/react-toolbox/lib/_colors.scss",
      {
        "theme-building": true
      },
      "client/theme/toolbox-theme.scss",
      "node_modules/flexboxgrid/dist/flexboxgrid.css"
    ],
    "ignorePaths": [
      "node_modules/react-flexbox-grid/(doc|spec|test|)/"
    ]
  }
```

If I include `css` in extensions, then I get errors from a lot of other files that I will probably have to ignore.

Do you know which should be the configuration? Sorry I am a total CSS module noob.

**Comment by akanix42** [comment]
Can you elaborate on "the errors had stopped but the package is not working neither."? Are you getting any errors now (if it builds successfully, also check the browser console).
Can you post a repro so I can take a look?
This should work without  `css` file parsing, as the files in `globalVariables` are read in directly.

**Comment by PolGuixe** [comment]
Basically the components did not have any class name. The class property was empty.

**Comment by akanix42** [comment]
OK, I've created [a working example](https://github.com/nathantreid/66-react-flexbox-grid).
It looks like the only big change is that you need to enable `css` file processing, so you will need to ignore the other files that are causing you errors (or if they are legacy CSS files that you application needs, use the `passthroughPaths` option to exclude them from CSS modules processing but still include their CSS in the output).

I also configured the flexboxgrid processing using `ignorePaths` to only process the `dist/flexboxgrid.css` file to help keep processing times low.

**Comment by sean-stanley** [comment]
Hi your example is no longer working with the latest version of react-flexbox-grid 1.1.4. I am going to have a play though and see if I can't get it working. 

Problem seems to be that now react-flexbox-grid is creating a different pattern for the class names than before. I don't have much experience using css modules but they look awesome and I'm sure there must be a way to get it to work. I'm using react-felxbox-grid in my non-meteor projects just really hoping to get the latest version working in Meteor now too.
