### ISSUE TITLE
unit testing react components

### ISSUE THREAD

**Issue by wojtkowiak** [nathantreid/meteor-css-modules#68]
Hey,
I am using css modules in React components and was recently trying to unit test them. Any thought how I could possibly run a code that uses your package without meteor context? I mean that for example when using `enzyme` I just usually import my component and do some testing. Now it will fail because I am importing a `scss` which of course will not work without meteor and your package.
I am just asking if you have any idea?
The same goes with trying to use `kadira-storybook`.

**Comment by akanix42** [comment]
I take it you are doing your testing without using `meteor test`? my package is only intended to wor within the Meteor context; to approximate using it without Meteor, I guess you'd have to use something like webpack with mocha-webpack and use a different CSS modules loader.

**Comment by wojtkowiak** [comment]
Yeah, I am trying to unit test my React components without Meteor context. It is just so much faster without Meteor.
Actually yesterday my team got it at least to the point where the test is compiled. They started with something like this in mocha. There will be some hassle to replicate fully the config we are using with your package but at least that's a good start. Maybe it would be useful to put something like this in the docs because to my best knowledge it is a very good practice to test React components in isolation without any app context running at all.

``` javascript

 const hook = require('css-modules-require-hook');
 const sass = require('node-sass');
 hook({
     extensions: [ '.scss', '.css' ],
     generateScopedName: '[local]___[hash:base64:5]',
     preprocessCss: ( data, file ) => sass.renderSync({ file }).css
});
```
