### ISSUE TITLE
Possible error on css-modules' dependencies?

### ISSUE THREAD

**Issue by Spiralis** [nathantreid/meteor-css-modules#69]
I am setting up one of my colleagues to help development on a project, but the project won't work on his computer. I have created a thread on this in the meteor forum [here](https://forums.meteor.com/t/meteor-build-error-cannot-find-module/28929), for reference. 

The error looks like this:

```
/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Processing Step: Babel compilation
Unable to compile imports/custom/components/Clock/Clock.mss
Error: Cannot find module './data/character-class-escape-sets.js'
Source: 
// <start of file>
 import modules from 'meteor/modules';
modules.addStyles("._imports_custom_components_Clock__Clock__root{\r\n    text-align: left;\r\n}\r\n\r\n/*# sourceMappingURL=Clock.mss.map */");
const styles = {"root":"_imports_custom_components_Clock__Clock__root"};
export { styles as default, styles };
// <end of file>

/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The full error log is included here: [Meteor error log.txt](https://github.com/nathantreid/meteor-css-modules/files/455338/Meteor.error.log.txt)

To be honest I am not sure whether this is a meteor or css-modules issue. But, I am posting the issue both places as I guess these are the best hopes I have of getting help.

**Comment by akanix42** [comment]
Nothing jumps out at me from that error - can you post a reproduction repo?

**Comment by Spiralis** [comment]
On his machine we were able to recreate this with a minimum amount of steps. 
1. Run `meteor create demo`
2. `cd demo`
3. Add `nathantreid:css-modules` to the `.meteor/packages` file
4. Run `meteor`

The same error message as above is shown (without the initial error message related to the inclusion of a `.mss` file in the linked to log).

Could this be a Windows "path too long" issue? It is a bit strange though, that it happens only on his Windows 10 installation, and not on my Win 10 installation.

**Comment by akanix42** [comment]
It certainly seems like it could be a path too long issue, given the length of the path: `C:\Users\ole\AppData\Local\.meteor\packages\nathantreid_css-modules\2.2.2\plugin.mss.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\node_modules\babel-plugin-transform-es2015-unicode-regex\node_modules\regexpu-core\rewrite-pattern.js`.
But it seems odd then that he would have the issue and you and I wouldn't (I develop primarily on Windows 10).

**Comment by akanix42** [comment]
The issue doesn't appear to be with my package itself, so I'd recommend creating an issue over here: https://github.com/meteor/meteor/issues.

**Comment by Spiralis** [comment]
Yes, indeed. This might just be a fluke thing though... Thanks.

**Comment by SPAHI4** [comment]
Same error too
