### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by juditgreskovits** [nathantreid/meteor-css-modules#7]
Would it be possible to omit "archMatching: 'web'" so that this could be used with server side rendering too?

**Comment by akanix42** [comment]
I _think_ that should be doable, I just need to add a filter so Meteor doesn't try to output the stylesheet when it's building for the server instead of for web.

**Comment by akanix42** [comment]
This was released in version 1.0.0. I haven't updated the documentation yet, but to enable client & server-side just add a `"specificArchitecture": false` option in the cssModules section of packages.json.

You can also use any other valid "archMatching" setting.
