### ISSUE TITLE
ignorePaths doesn't work?

### ISSUE THREAD

**Issue by shaunnez** [nathantreid/meteor-css-modules#70]
packages/nathantreid_css-modules/.2.2.2.1e9manq++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/mss/node_modules/postcss/lib/input.js:61:22:

"cssModules": {
      "ignorePaths": [
        "node_modules/convert-source-map/_",
        "node_modules/convert-source-map/"
      ],
      "extensions": [
        "scss"
      ],
      "globalVariables": [
        "node_modules/react-toolbox/lib/_colors.scss",
        {
          "theme-building": true
        },
        "client/toolbox-theme.scss"
      ],
      "outputJsFilePath": {
        "._node_modules/.*": "{dirname}/{basename}.js"
      },
      "explicitIncludes": [
        "node_modules/react-toolbox"
      ]
    }

**Comment by akanix42** [comment]
Are you still experiencing this issue with the latest version of the package? If so, feel free to reopen this issue.
If you do reopen the issue, please provide the following info:
1. What you are trying to do.
2. What is actually happening.
3. If possible, a github repo containing a reproduction so I can quickly see the issue for myself.

Thanks!
