### ISSUE TITLE
How do you supply browser list when using autoprefixer?

### ISSUE THREAD

**Issue by dgroch** [nathantreid/meteor-css-modules#80]
When using the postcss plugin autoprefixer, how do you supply the browser list?
Is it done via the options hash in package.json?

eg 

```
"postcssPlugins": {
  "autoprefixer": { "browsers": ["iOS >= 8"] }
}
```

**Comment by akanix42** [comment]
What you have looks right at a glance - is it not working for you?

**Comment by dgroch** [comment]
Yup. I think it's working fine as I see prefixes everywhere!
