### ISSUE TITLE
Segmentation fault: 11th nathantreid:css...  \

### ISSUE THREAD

**Issue by Furqankhanzada** [nathantreid/meteor-css-modules#81]
I am getting this error after updating to METEOR@1.4.2.3

![screen shot 2016-12-03 at 5 00 11 pm](https://cloud.githubusercontent.com/assets/2400215/20859222/7fe26058-b97a-11e6-9db0-9564faa38c36.png)

when i remove this error goes but project not run cos its required when we use react toolbox with meteor.

**Comment by derzinn** [comment]
Same here.

**Comment by Furqankhanzada** [comment]
@derzinn any luck ?

**Comment by akanix42** [comment]
@Furqankhanzada Can you post a reproduction repo on github? I don't experience the error when I create a new app with meteor create and add nathantreid:css-modules, so a reproduction would make it much easier to dig into this. Thanks!

**Comment by Furqankhanzada** [comment]
@nathantreid clone this repo https://github.com/AppBakerZ/FinanceBakerZ and update meteor version to latest. then you will be able to reproduce error.

**Comment by Furqankhanzada** [comment]
Its no more with latest meteor version.
