### ISSUE TITLE
Problem with reloading or caching

### ISSUE THREAD

**Issue by arggh** [nathantreid/meteor-css-modules#87]
I've been experiencing this for a while now. The styles-objects I import from `m.css` files sometimes stop reloading. 

1. Coding happily
2. Suddenly my CSS declarations seem to have no effect whatsoever
3. `console.log(styles)` -> wrong/old object keys!
4. making changes to the `html`, `js` or `m.css` has no effect
5. kill meteor and restart
6. works again

It might have something to do with renaming. I just now had an old stylesheet with an `scss` suffix containing an empty CSS rule `.myElement {}`

I then renamed the file, so the suffix was `m.css` (which is processed by CSS modules in my config) and tried using it with CSS modules and *bam*, the file got stuck in the limbo. Importing it just gave me the empty styles under key `myElement`. Changing the `m.css`-files contents to `.anotherElement { color: red }` would have no effect.

**Comment by arggh** [comment]
Fyi, https://github.com/meteor/meteor/issues/9054

**Comment by akanix42** [comment]
Closing due to the updates made by Meteor core in the referenced issue. If this is still an issue, please reopen it!
