### ISSUE TITLE
Pre 1.3 jsx support

### ISSUE THREAD

**Issue by abhiaiyer91** [nathantreid/meteor-css-modules#9]
How would you like this done, I can send over a PR

**Comment by akanix42** [comment]
Thanks!

The first part is to add a jsx compiler to handle jsx files (the only difference should be the `BabelCompiler({react: true})`: https://github.com/nathantreid/meteor-css-modules-js-compiler/blob/master/js-compiler.js

The second bit is to register this compiler: https://github.com/nathantreid/meteor-css-modules/blob/master/plugins.js

The last (and hardest) part is to figure out the last release of https://github.com/meteor/react-packages that supported 1.2, fork it, replace references to the jsx package with the CSS modules jsx compiler, publish it, and import it into the CSS modules package.

**Comment by akanix42** [comment]
This is a pretty old issue, so I'm going to close it for now. Feel free to reopen it if necessary.
