### ISSUE TITLE
Imported SCSS files are not merged with final CSS file?

### ISSUE THREAD

**Issue by dnish** [nathantreid/meteor-css-modules#97]
Hey,
if I import some .scss files within my React components (all files are saved in /imports), the styles are not appended to the merges css file, instead I have a lot of inline style tags with all of my renamed classes. Is this the normal behavior when using css modules?

**Comment by akanix42** [comment]
This is normal behavior for Meteor when using css (scss, etc) files in the imports directory.

**Comment by dnish** [comment]
Ah okay, I just thought that the plugin bundles it.
