### ISSUE TITLE
Can this be used on angular 1?

### ISSUE THREAD

**Issue by d4lek** [nathantreid/meteor-css-modules#98]
Hi, just wondering if this package could be used on Angular 1?

Thanks

**Comment by akanix42** [comment]
I haven't tested this with Angular 1, but I don't see any reason why it wouldn't work. It should be usable with anything that allows you to pass in class names via javascript.

**Comment by akanix42** [comment]
If you run into any issues using this package with Angular, please let me know. I'm going to close this for now.
